name: CI

on: 
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: setup environment
      run: docker-compose up -d --build
    - name: Run tests
      run: docker exec acacia-frontend npm test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage/clover.xml
        flags: unittests
        name: codecov-umbrella
